services:
  express_app:
    build: .
    container_name: express_app
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: express_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
