services:
  express_app:
    image: satchel47/express_app:latest
    container_name: express_app
    ports:
      - 8080:8080
    labels:
      - com.centurylinklabs.watchtower=true
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    command: express_app
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
